name: build-and-push
on: [push]
  # schedule: 
  #   - cron: '0 20 * * *'
    
jobs: 
  build:
    name: "Python 3.7"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: 3.7
      - name: update_graph
        run: |
          pip3 install -r requirements.txt 
          python3 nations_and_regions.py
      - name: push_to_repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          git commit -m "Update graph"
          git push
          
      - uses: "actions/checkout@v2"
      - uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: push_to_webapp
        run: |
          cd webapp
          az webapp up
